### ISSUE TITLE
预训练模型失效了

### ISSUE THREAD

**Issue by dcdethan** [tommyMessi/crnn_ctc-centerloss#3]
你好，百度网盘的预训练模型链接失效了，请问可以再提供一下吗？

**Comment by tommyMessi** [comment]
已经更新了

**Comment by dcdethan** [comment]
好的，多谢

**Comment by ReverseSystem001** [comment]
> 好的，多谢

兄弟，使用预训练模型，调试跑通test.py后，你那能输出正确结果吗

**Comment by dcdethan** [comment]
> > 好的，多谢
> 
> 兄弟，使用预训练模型，调试跑通test.py后，你那能输出正确结果吗

我再试一下吧，还是好久前弄的

**Comment by ReverseSystem001** [comment]
嗯嗯，好的，我这边一顿改之后，能跑通了，但是测试集上结果都不对



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年10月28日(周四) 晚上6:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tommyMessi/crnn_ctc-centerloss] 预训练模型失效了 (#3)




   
好的，多谢
  
兄弟，使用预训练模型，调试跑通test.py后，你那能输出正确结果吗
  
我再试一下吧，还是好久前弄的
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
